// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePhoto = "photos"

// Photo mapped from table <photos>
type Photo struct {
	ID              int32      `gorm:"column:id;primaryKey" json:"id"`
	DestinationPath string     `gorm:"column:destination_path;not null" json:"destination_path"`
	FileName        string     `gorm:"column:file_name;not null" json:"file_name"`
	RelPath         string     `gorm:"column:rel_path;not null" json:"rel_path"`
	SizeBytes       int32      `gorm:"column:size_bytes;not null" json:"size_bytes"`
	Sha256          string     `gorm:"column:sha256" json:"sha256"`
	BackedUpAt      time.Time  `gorm:"column:backed_up_at;not null" json:"backed_up_at"`
	Status          string     `gorm:"column:status;not null;default:'active'" json:"status"`
	Description     string     `gorm:"column:description;type:TEXT" json:"description"`
	PhotoTags       []PhotoTag `gorm:"foreignKey:PhotoID;references:ID" json:"photo_tags"`
}

// TableName Photo's table name
func (*Photo) TableName() string {
	return TableNamePhoto
}
