// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePhotoTag = "photo_tags"

// PhotoTag mapped from table <photo_tags>
type PhotoTag struct {
	PhotoID   int32  `gorm:"column:photo_id;not null" json:"photo_id"`
	TagID     int32  `gorm:"column:tag_id;not null" json:"tag_id"`
	Source    string `gorm:"column:source;not null;default:'ai'" json:"source"`
	Tag       Tag    `gorm:"foreignKey:TagID;references:ID" json:"tag"`
	PhotoTags Photo  `gorm:"foreignKey:PhotoID;references:ID" json:"photo_tags"`
}

// TableName PhotoTag's table name
func (*PhotoTag) TableName() string {
	return TableNamePhotoTag
}
