// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIntegrity(arg1) {
  return window['go']['service']['BackupService']['CheckIntegrity'](arg1);
}

export function CleanAll() {
  return window['go']['service']['BackupService']['CleanAll']();
}

export function Delete(arg1, arg2) {
  return window['go']['service']['BackupService']['Delete'](arg1, arg2);
}

export function GetDest() {
  return window['go']['service']['BackupService']['GetDest']();
}

export function GetSource() {
  return window['go']['service']['BackupService']['GetSource']();
}

export function ListDB(arg1) {
  return window['go']['service']['BackupService']['ListDB'](arg1);
}

export function ListDest(arg1) {
  return window['go']['service']['BackupService']['ListDest'](arg1);
}

export function ListDestFiles(arg1) {
  return window['go']['service']['BackupService']['ListDestFiles'](arg1);
}

export function ListSource() {
  return window['go']['service']['BackupService']['ListSource']();
}

export function ListSourceFiles() {
  return window['go']['service']['BackupService']['ListSourceFiles']();
}

export function Move(arg1, arg2) {
  return window['go']['service']['BackupService']['Move'](arg1, arg2);
}

export function SelectDestDialog() {
  return window['go']['service']['BackupService']['SelectDestDialog']();
}

export function SelectSourceDialog() {
  return window['go']['service']['BackupService']['SelectSourceDialog']();
}

export function SetContext(arg1) {
  return window['go']['service']['BackupService']['SetContext'](arg1);
}

export function SetDest(arg1) {
  return window['go']['service']['BackupService']['SetDest'](arg1);
}

export function SetSource(arg1) {
  return window['go']['service']['BackupService']['SetSource'](arg1);
}
