// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {model} from '../models';
import {context} from '../models';

export function CheckIntegrity(arg1:string):Promise<service.IntegrityResult>;

export function CleanAll():Promise<void>;

export function Delete(arg1:Array<string>,arg2:boolean):Promise<number>;

export function GetDest():Promise<string>;

export function GetSource():Promise<string>;

export function ListDB(arg1:string):Promise<Array<model.Photo>>;

export function ListDest(arg1:string):Promise<Array<string>>;

export function ListDestFiles(arg1:string):Promise<Array<service.FileItem>>;

export function ListSource():Promise<Array<string>>;

export function ListSourceFiles():Promise<Array<service.FileItem>>;

export function Move(arg1:Array<string>,arg2:boolean):Promise<service.MoveSummary>;

export function SelectDestDialog():Promise<string>;

export function SelectSourceDialog():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDest(arg1:string):Promise<service.IntegrityResult>;

export function SetSource(arg1:string):Promise<void>;
