// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';
import {service} from '../models';
import {context} from '../models';
import {repository} from '../models';

export function AnalyzePhoto(arg1:string):Promise<dto.VisionResult>;

export function CheckIntegrity(arg1:string):Promise<dto.IntegrityResult>;

export function CleanAll():Promise<void>;

export function Delete(arg1:Array<string>,arg2:boolean):Promise<number>;

export function GetDest():Promise<string>;

export function GetSource():Promise<string>;

export function ListDB(arg1:string):Promise<Array<model.Photo>>;

export function ListDest(arg1:string):Promise<Array<string>>;

export function ListDestFiles(arg1:string):Promise<Array<dto.FileItem>>;

export function ListSource():Promise<Array<string>>;

export function ListSourceFiles():Promise<Array<dto.FileItem>>;

export function Move(arg1:Array<string>,arg2:boolean):Promise<dto.MoveSummary>;

export function SelectDestDialog():Promise<string>;

export function SelectSourceDialog():Promise<string>;

export function SetAiVision(arg1:service.AiVisionService):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDest(arg1:string):Promise<dto.IntegrityResult>;

export function SetSource(arg1:string):Promise<void>;

export function SetTagRepo(arg1:repository.TagRepository):Promise<void>;
