// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';

export function AnalyzePhoto(arg1:string):Promise<dto.VisionResult>;

export function CheckIntegrity(arg1:string):Promise<dto.IntegrityResult>;

export function DeletePhotos(arg1:Array<string>,arg2:boolean):Promise<number>;

export function GetDestPath():Promise<string>;

export function GetPhotoThumbnail(arg1:string):Promise<string>;

export function GetPhotoThumbnails(arg1:Array<string>):Promise<Record<string, string>>;

export function GetSourcePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListDBPhotos(arg1:string):Promise<Array<model.Photo>>;

export function ListDestFileItems(arg1:string):Promise<Array<dto.FileItem>>;

export function ListDestPhotos(arg1:string):Promise<Array<string>>;

export function ListSourceFileItems():Promise<Array<dto.FileItem>>;

export function ListSourcePhotos():Promise<Array<string>>;

export function MovePhotos(arg1:Array<string>,arg2:boolean):Promise<dto.MoveSummary>;

export function SelectDestFolder():Promise<dto.IntegrityResult>;

export function SelectSourceFolder():Promise<string>;

export function SetDestPath(arg1:string):Promise<dto.IntegrityResult>;

export function SetSourcePath(arg1:string):Promise<void>;
