// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {model} from '../models';

export function CheckIntegrity(arg1:string):Promise<service.IntegrityResult>;

export function DeletePhotos(arg1:Array<string>,arg2:boolean):Promise<number>;

export function GetDestPath():Promise<string>;

export function GetSourcePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListDBPhotos(arg1:string):Promise<Array<model.Photo>>;

export function ListDestFileItems(arg1:string):Promise<Array<service.FileItem>>;

export function ListDestPhotos(arg1:string):Promise<Array<string>>;

export function ListSourceFileItems():Promise<Array<service.FileItem>>;

export function ListSourcePhotos():Promise<Array<string>>;

export function MovePhotos(arg1:Array<string>,arg2:boolean):Promise<service.MoveSummary>;

export function SelectDestFolder():Promise<service.IntegrityResult>;

export function SelectSourceFolder():Promise<string>;

export function SetDestPath(arg1:string):Promise<service.IntegrityResult>;

export function SetSourcePath(arg1:string):Promise<void>;
