// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIntegrity(arg1) {
  return window['go']['main']['App']['CheckIntegrity'](arg1);
}

export function DeletePhotos(arg1, arg2) {
  return window['go']['main']['App']['DeletePhotos'](arg1, arg2);
}

export function GetDestPath() {
  return window['go']['main']['App']['GetDestPath']();
}

export function GetPhotoThumbnail(arg1) {
  return window['go']['main']['App']['GetPhotoThumbnail'](arg1);
}

export function GetPhotoThumbnails(arg1) {
  return window['go']['main']['App']['GetPhotoThumbnails'](arg1);
}

export function GetSourcePath() {
  return window['go']['main']['App']['GetSourcePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDBPhotos(arg1) {
  return window['go']['main']['App']['ListDBPhotos'](arg1);
}

export function ListDestFileItems(arg1) {
  return window['go']['main']['App']['ListDestFileItems'](arg1);
}

export function ListDestPhotos(arg1) {
  return window['go']['main']['App']['ListDestPhotos'](arg1);
}

export function ListSourceFileItems() {
  return window['go']['main']['App']['ListSourceFileItems']();
}

export function ListSourcePhotos() {
  return window['go']['main']['App']['ListSourcePhotos']();
}

export function MovePhotos(arg1, arg2) {
  return window['go']['main']['App']['MovePhotos'](arg1, arg2);
}

export function SelectDestFolder() {
  return window['go']['main']['App']['SelectDestFolder']();
}

export function SelectSourceFolder() {
  return window['go']['main']['App']['SelectSourceFolder']();
}

export function SetDestPath(arg1) {
  return window['go']['main']['App']['SetDestPath'](arg1);
}

export function SetSourcePath(arg1) {
  return window['go']['main']['App']['SetSourcePath'](arg1);
}
